import json
from pprint import pformat

from cafe.engine.models.base import AutoMarshallingModel
from six import iteritems


class SettingsResponse(AutoMarshallingModel):

    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, DataFrom, DataTo, LastUpdate, NextUpdate, Transactions, version):
        """
        DataStatus - a model defined in Swagger

        """

        self.version = version
        self.transactions = Transactions
        self.last_update = LastUpdate
        self.next_update = NextUpdate
        self.data_from = DataFrom
        self.data_to = DataTo

    @classmethod
    def _json_to_obj(cls, serialized_str):
        serialized_str = json.loads(serialized_str)
        entity = SettingsResponse(DataFrom=serialized_str.get("DataFrom"),
                            DataTo=serialized_str.get("DataTo"),
                            LastUpdate=serialized_str.get("LastUpdate"),
                            NextUpdate=serialized_str.get("NextUpdate"),
                            Transactions=serialized_str.get("Transactions"),
                            version=serialized_str.get("version"),)
        return entity

